name: Postman collection workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 1-5' #8am Sydney time monday to friday
jobs:
  run-postman-jobs:
    runs-on: ec2-githubrunner #githubrunner

    steps:
      - name: checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install node.js and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'
      - name: Install Newman and Html-extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the postman collection with newman
        run: |
          newman run 'Inwarranty-flow Collection.postman_collection.json' \
          -e QA.postman_environment.json \
          -d testData.csv \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html
                  
     
      - name: Archive Newman reports
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html
          
      - name: Creating github page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with: 
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: newman/

      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix InwarrantyFlow Test Automation
          to: sithara.sreedharan@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hi,
            Phoenix Inwarranty flow API tests has been executed and please find the attched report:
            https://sitharasreedharan.github.io/Phoenix-Inwarranty-Flow/
          
    
         
      
          
          
      
      
      
      
    
